Use --format in skopeo to extract container label  instead of using grep
openshift-cnv/cnv-fbc pull request #15732
Opened 2024-12-16 19:15 UTC by jordigilh

@tiraboschi This change uses a `skopeo` formatting flag to extract the `url` field value without the need to generate all fields and then filter with grep.

I've tested it locally and it generated the same output.

PD: I've used this repo as reference to generate our equivalent RHDH `orchestrator-fbc` that I wanted to contribute something back after all the work I've benefited from by this repository.

2024-12-16 19:28 UTC, jordigilh commented
/assign @Axuba

2024-12-17 11:50 UTC, Axuba requested changes

2024-12-17 15:28 UTC, jordigilh commented on generate-fbc.sh
>          tag=${tag1/\",/}
Done! 😄

2024-12-17 19:54 UTC, jordigilh commented on generate-fbc.sh
>        tag=${tag1/\",/}
Done

2024-12-18 07:24 UTC, Axuba approved these changes

2024-12-18 07:25 UTC, Axuba commented
/lgtm

2024-12-18 12:00 UTC, Axuba commented
Merging as the pipeline fails because of the secret is not passed to the fork.

2024-12-18 12:00 UTC, merged